#!/usr/bin/env ruby
require "rails/gke"

project = {}
config_path = "./config/initializers/rails-gke.rb"
if File.exist? config_path
  puts "This process will Overwrite `#{config_path}` file. OK / Enter"
  confirm = gets.chomp
  exit unless confirm == ""
end

begin
  puts "Google Cloud PROJECT_ID:      (default: elsoul2)"
  project[:project_id] = gets.chomp
  project[:project_id] == "" ? project[:project_id] = "elsoul2" : true
  puts "Your APP name:      (default: grpc-td-cluster)"
  project[:app] = gets.chomp
  project[:app] == "" ? project[:app] = "grpc-td-cluster" : true
  puts "VPC Network Name:          (default: default)"
  project[:network] = gets.chomp
  project[:network] == "" ? project[:network] = "default" : true
  puts "Instance MachineType:       (default: custom-1-6656)"
  project[:machine_type] = gets.chomp
  project[:machine_type] == "" ? project[:machine_type] = "custom-1-6656" : true
  puts "Zone:           (default: us-central1-a)"
  project[:zone] = gets.chomp
  project[:zone] == "" ? project[:zone] = "us-central1-a" : true
  puts "Domain:          (default: el-soul.com)"
  project[:domain] = gets.chomp
  project[:domain] == "" ? project[:domain] = "el-soul.com" : true
  puts "Google Application Credentials Path:      (default: ./config/credentials.json)"
  project[:google_application_credentials] = gets.chomp
  project[:google_application_credentials] == "" ? project[:google_application_credentials] = "./config/credentials.json" : true

  puts project
  puts "Enter to finish set up!"
  confirm = gets.chomp
  raise "Retry" unless confirm == ""
rescue
  retry
end


FileUtils.mkdir_p "config/initializers" unless File.directory? "config/initializers"
path = "config/initializers/rails-gke.rb"
File.open(path, "w") do |f|
  f.write <<~EOS
    Rails::Gke.configure do |config|
      config.project_id = "#{project[:project_id]}"
      config.app = "#{project[:app]}"
      config.network = "#{project[:network]}"
      config.machine_type = "#{project[:machine_type]}"
      config.zone = "#{project[:zone]}"
      config.domain = "#{project[:domain]}"
      config.google_application_credentials = "#{project[:google_application_credentials]}"
    end
  EOS
end
puts "You Are All Set!!"
puts "config at ./config/initializers/rails-gke.rb"
